### ISSUE TITLE
is there a way to manually enter the bpm?

### ISSUE THREAD

**Issue by OilSubjectLoss7** [idkman2021/BigOuncesAudioEffects#3]
i have stem files and other than the drums, it can't detect the bpm

**Comment by inikishev** [comment]
> i have stem files and other than the drums, it can't detect the bpm

if those stem files are from the same project as the drums, the drums song object will have beatmap variable after you generate it, so you can do something like  beats = drums.beatmap, and then create stem object, and do stem.beatmap = beats. 

Or you can create your own beatmap, for example for 44100hz 140 bpm, it will be 44100 / (140/60) = 18900 samples per beat (i think), so you can create a list or array like this: [i*18900 for i in range (len(audio)/18900)], and then when you create stems song object, add beatmap = that list attribute.

I will add a way to manually enter the bpm because that is easy to do. also keep in mind it will require shift to be entered as well, because first beat is not always perfectly on the 0.0 second.

if you are using google collab or hugging face, you can add this code to google collab. i can explain what code you need in more details if you want.

**Comment by OilSubjectLoss7** [comment]
I found a way but it's very time consuming, `mp3 > beatman > demucs`. Demucs is slow as hell but it's fine. Can't wait for the bpm option. I use hf, collab is was too slow for me.
